{
 "title": "Gin Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "range",
    "query": "1m, 5m, 10m, 30m, 1h, 3h, 6h, 12h, 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Response Time [$range]",
   "type": "timeseries",
   "description": "This metric measures the average time it takes for an application to respond to a request. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gin_request_duration_sum[$range])) / sum(rate(gin_request_duration_count[$range]))\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS) [$range]",
   "type": "timeseries",
   "description": "This metric measures the rate at which your application receives and processes incoming requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gin_request_total[$range]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "PV Rate [$range]",
   "type": "gauge",
   "description": "Application request rate every  [$range]",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(gin_request_total[$range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (gin_uri_request_total)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code, instance) (gin_uri_request_total)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out [$range]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gin_request_body_total[$range])",
     "legendFormat": "broker-in"
    },
    {
     "expr": "rate(gin_response_body_total[$range])",
     "legendFormat": "broker-out"
    }
   ]
  },
  {
   "title": "Slow Request (default 5s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, instance) (gin_slow_request_total)",
     "legendFormat": "{{instance}}-{{uri}}"
    }
   ]
  }
 ]
}