apiVersion: 1
datasources:
  - name: "prometheus"
    type: prometheus
    url: http://prometheus:9090
    access: "proxy"
    basicAuth: false
    isDefault: false
    editable: false
    version: 1
    uid: "PBFA97CFB590B2093"
    jsonData:
      storage: http
