apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-storage
      containers:
      - name: postgres
        image: postgres:14.2
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: users
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                psql -U postgres -c "CREATE SEQUENCE public.user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;"
                psql -U postgres -c "CREATE TABLE public.users (id integer DEFAULT nextval('public.user_id_seq'::regclass) NOT NULL, email character varying(255), first_name character varying(255), last_name character varying(255), password character varying(60), user_active integer DEFAULT 0, created_at timestamp without time zone, updated_at timestamp without time zone);"
                psql -U postgres -c "ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);"
                psql -U postgres -c "INSERT INTO \"public\".\"users\"(\"email\",\"first_name\",\"last_name\",\"password\",\"user_active\",\"created_at\",\"updated_at\") VALUES (E'admin@example.com',E'Admin',E'User',E'$2a$12$1zGLuYDDNvATh4RA4avbKuheAMpb1svexSzrQm7up.bnpwQHs0jNe',1,E'2022-03-14 00:00:00',E'2022-03-14 00:00:00');"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
